image: "macaronios/terragon-minimal:latest-amd64"

package_dir: /mark
prelude:
- anise i --sync-repos curl tar -y --cleanup
- mkdir -p /mark/collections/mark/
- >-
  curl -L https://mark-os.macaronios.org/mark-stages-terragon/terragon/${RELEASE}/x86-64bit/generic_64/${STAGE_VERSION}/${STAGE_NAME}-x86-64bit-generic_64-mark%2Bterragon%2Bmark-xl-${STAGE_VERSION}.tar.xz
  -o /mark/collections/mark/${STAGE_NAME}-mark-xl.tar.xz
env:
- STAGE_VERSION={{ ( index .Values.labels "package.version" ) }}
- STAGE_NAME=stage3
- RELEASE=mark
